[book]
authors = ["Lucas Zawacki"]
language = "pt-BR"
src = "src"
title = "Tecnologia e Classe"
description = "Roteiros dos vídeos do canal Tecnologia e Classe."

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/Soberana-TV/tecnologiaeclasse/tree/main"
cname = "teclas.soberana.tv"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.embed]

[rss]
title = "Roteiros Tecnologia e Classe"
description = "Feed dos roteiros de vídeos do canal Tecnologia e Classe"
base_url = "https://teclas.soberana.tv"
